"""add_google_calendar_credentials_to_agent

Revision ID: 6d298fe98456
Revises: 742fb332c50b
Create Date: 2026-07-02 16:03:46.298630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d298fe98456'
down_revision: Union[str, Sequence[str], None] = '742fb332c50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_client_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_client_secret', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_client_secret')
        batch_op.drop_column('google_calendar_client_id')

    # ### end Alembic commands ###
