"""add_google_calendar_and_stt_timezone

Revision ID: 742fb332c50b
Revises: a6b7c8d9e0f1
Create Date: 2026-07-02 15:56:39.709242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742fb332c50b'
down_revision: Union[str, Sequence[str], None] = 'a6b7c8d9e0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    default_bool = sa.text('0') if is_sqlite else sa.false()

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_connected', sa.Boolean(), nullable=False, server_default=default_bool))
        batch_op.add_column(sa.Column('google_calendar_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stt_provider', sa.String(length=50), nullable=False, server_default='groq_whisper'))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=False, server_default='America/Bogota'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('stt_provider')
        batch_op.drop_column('google_calendar_email')
        batch_op.drop_column('google_calendar_connected')
        batch_op.drop_column('google_calendar_refresh_token')

    # ### end Alembic commands ###
