"""add_whatsapp_message_id

Revision ID: aa24728a4341
Revises: 2811bd324735
Create Date: 2026-06-09 17:07:28.410074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa24728a4341'
down_revision: Union[str, Sequence[str], None] = '2811bd324735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_whatsapp_message_id'), ['whatsapp_message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_whatsapp_message_id'))
        batch_op.drop_column('whatsapp_message_id')

    # ### end Alembic commands ###
