"""add_whatsapp_qr_fields

Revision ID: fbf8b351835b
Revises: 6d298fe98456
Create Date: 2026-07-06 12:27:33.190417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf8b351835b'
down_revision: Union[str, Sequence[str], None] = '6d298fe98456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    default_bool = sa.text('0') if is_sqlite else sa.false()

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_provider', sa.String(length=50), nullable=False, server_default='meta_cloud'))
        batch_op.add_column(sa.Column('whatsapp_qr_instance_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_qr_instance_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_qr_connected', sa.Boolean(), nullable=False, server_default=default_bool))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_qr_connected')
        batch_op.drop_column('whatsapp_qr_instance_token')
        batch_op.drop_column('whatsapp_qr_instance_name')
        batch_op.drop_column('whatsapp_provider')

    # ### end Alembic commands ###
